name: 'cmake build'
description: 'GitHub Action for coverity scan builds done by cmake'
author: 'Stephan Gatzka <@gatzka>'
inputs: 
  coverity_token:
    description: 'coverity access token'
    required: true 
  install_deps:
    description: 'User defined script to install build dependencies in ubuntu'
    required: false 
  cmake_build_type:
    description: 'cmake build type like Debug|Release'
    required: false 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.coverity_token}}
    - ${{ inputs.install_deps}}
    - ${{ inputs.cmake_build_type}}

